// @ts-check

/** @typedef {{id: string, displayName: string, textureKey: string, sizeTier: number, collisionRadius: number, scoreValue: number, coinValue: number, baseSpeed: number, turnRate: number, behaviorId: string, behaviorParams: Readonly<Record<string, number>>}} FishDefinition */

/** @type {readonly FishDefinition[]} */
export const fishCatalog = Object.freeze(
  [
    {
      id: 'minnow',
      displayName: 'Minnow',
      textureKey: 'fish-minnow',
      sizeTier: 1,
      collisionRadius: 12,
      scoreValue: 1,
      coinValue: 1,
      baseSpeed: 100,
      turnRate: 2,
      behaviorId: 'wander',
      behaviorParams: Object.freeze({}),
    },
    {
      id: 'sardine',
      displayName: 'Sardine',
      textureKey: 'fish-sardine',
      sizeTier: 1,
      collisionRadius: 15,
      scoreValue: 2,
      coinValue: 2,
      baseSpeed: 165,
      turnRate: 4,
      behaviorId: 'flee',
      behaviorParams: Object.freeze({}),
    },
    {
      id: 'pufferfish',
      displayName: 'Pufferfish',
      textureKey: 'fish-pufferfish',
      sizeTier: 2,
      collisionRadius: 19,
      scoreValue: 6,
      coinValue: 6,
      baseSpeed: 90,
      turnRate: 2,
      behaviorId: 'wander',
      behaviorParams: Object.freeze({}),
    },
    {
      id: 'anchovy',
      displayName: 'Anchovy',
      textureKey: 'fish-anchovy',
      sizeTier: 1,
      collisionRadius: 13,
      scoreValue: 2,
      coinValue: 2,
      baseSpeed: 145,
      turnRate: 4,
      behaviorId: 'school',
      behaviorParams: Object.freeze({}),
    },
    {
      id: 'parrotfish',
      displayName: 'Parrotfish',
      textureKey: 'fish-parrotfish',
      sizeTier: 2,
      collisionRadius: 20,
      scoreValue: 5,
      coinValue: 5,
      baseSpeed: 205,
      turnRate: 5,
      behaviorId: 'flee',
      behaviorParams: Object.freeze({}),
    },
    {
      id: 'golden-fish',
      displayName: 'Golden Fish',
      textureKey: 'fish-golden',
      sizeTier: 2,
      collisionRadius: 18,
      scoreValue: 12,
      coinValue: 12,
      baseSpeed: 300,
      turnRate: 6,
      behaviorId: 'dash',
      behaviorParams: Object.freeze({
        dashSpeed: 360,
        dashDurationMs: 600,
        dashCooldownMs: 1800,
        approachDistance: 170,
      }),
    },
    {
      id: 'grouper',
      displayName: 'Grouper',
      textureKey: 'fish-grouper',
      sizeTier: 3,
      collisionRadius: 28,
      scoreValue: 20,
      coinValue: 20,
      baseSpeed: 105,
      turnRate: 2,
      behaviorId: 'wander',
      behaviorParams: Object.freeze({}),
    },
  ].map((fish) => Object.freeze(fish)),
);

export const fishIds = Object.freeze(new Set(fishCatalog.map((fish) => fish.id)));
